apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
      - name: subscriber
        image: gcr.io/cicd-426201/subscriber-app:v12
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "34.132.125.37"
        - name: DB_NAME
          value: "appdb"
        - name: DB_USER
          value: "root"
        - name: DB_PASS
          value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: subscriber
spec:
  selector:
    app: subscriber
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
